name: dockertest

# When a new release is published on GitHub, this workflow checks if the Docker
# image can successfully be built from the Dockerfile. The workflow can also be
# triggered manually

on:
  release:
    types:
      - published
  workflow_dispatch:
  
jobs:
  docker:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out a copy of the repository

      - name: Build image
        run: docker build . --file Dockerfile
