name: Run SearchSECO

on:
  push:

jobs:
  run-searchseco:
    name: "Run SearchSECO"
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull searchseco/controller

      - name: Run SearchSECO
        run: docker run --rm --name controller-container --entrypoint="./controller/build/searchseco" -e "github_token=${{secrets.GITHUB_TOKEN}}" -e "worker_name=test" searchseco/controller check https://github.com/rowins/test